### ISSUE TITLE
Don't initialize `buildSrc` if it is already present

### ISSUE THREAD

**Issue by henrik242** [jmfayard/buildSrcVersions#107]
If `rootProject.buildFileName` is set to something else than build.gradle.kts, buildSrcVersions should honor that file name when creating/updating that file.

---

*Edit from @jmfayard :* 

what would be need to be done here is to not initialize the `buildSrc` at all if we detect that it's already present (by looking for `buildSrc/{settings,build}.gradle(.kts)`

See https://github.com/jmfayard/buildSrcVersions/blob/ec3880ce72f736f30bb6c7bed413c9b67a28e84f/plugin/src/main/kotlin/de/fayard/BuildSrcVersionsTask.kt#L38-L59

**Comment by jmfayard** [comment]
Sounds legit. 
What should the plugin do exactly?
I would say, just do nothing if the user has already setup a `buildSrc`.
The creation is meant for users who don't have one.

**Comment by henrik242** [comment]
I just noticed that the plugin created a build.gradle.kts when I already had a buildSrc.gradle.kts (defined in settings. gradle.kts). I haven't looked into other scenarios really :)

**Comment by jmfayard** [comment]
@henrik242 that's fine, thank you for your valuable feedback :) 

I have updated your ticket for if someone wants to pick it up.

**Comment by jmfayard** [comment]
I am closing this because my long term plan is to focus on refreshVersions which generate a single file `versions.properties` #107

We are not there quite yet, so stay tuned
