### ISSUE TITLE
refreshVersions removes newline at EOF in gradle.properties

### ISSUE THREAD

**Issue by serebit** [jmfayard/buildSrcVersions#108]
**Checklist**

- [x] I verified that the task `./gradlew :dependencyUpdates` works correctly. If that's not the case, it's better to submit a bug-report to https://github.com/ben-manes/gradle-versions-plugin 
- [x] I tried to reproduce the bug within `sample-groovy`, `sample-kotlin` or `sample-versionsOnlyMode` 
- [x] I have run with `$ ./gradlew --scan buildSrcVersions` or `$./gradlew --scan refreshVersions` to [provide a Build Scan URL](https://dev.to/jmfayard/the-one-gradle-trick-that-supersedes-all-the-others-5bpg)
 
**Describe the bug**
If the gradle.properties file has a newline between the EOF and the last version property, running `./gradlew refreshVersions` removes the newline.

**To Reproduce**

Add a newline to the end of gradle.properties just after the version properties, and then run `./gradlew refreshVersions`.

**Expected behavior**
The newline should remain at the end of the file.

**Comment by jmfayard** [comment]
thanks, indeed I noted this as well and it needs to be fixed

**Comment by jmfayard** [comment]
The issue will be moot in a future release because instead of hacking together `gradle.properties`, I use a proper separate file: `versions.properties`
