### ISSUE TITLE
Dependency has no version

### ISSUE THREAD

**Issue by abitofhelp** [jmfayard/buildSrcVersions#23]
_Context: [buildSrcVersions](https://github.com/jmfayard/buildSrcVersions) is a Gradle plugin that makes it easier to manage your dependencies inside your IDE. It extracts all your dependencies and search for available dependencies updates._

Some plugins like `io.vertx.vertx-plugin` pin a dependency version. In that case, buildSrcVersions generate the following code

```kotlin
// sample-groovy/build.gradle
plugins {
    id "io.vertx.vertx-plugin" version "0.3.1"
    id 'de.fayard.buildSrcVersions' version '0.4.0'
}
dependencies {
    implementation "io.vertx:vertx-web"
}

// Libs.kt
object Libs {
    const val vertx_core: String = "io.vertx:vertx-core"
}
// Versions.kt
object Versions {
    const val vertx_core: String = "none" // No version. See buildSrcVersions#23
} 
```

What follows is the problem that appears in version 0.3.2 and before in that case

--- 
Hello, 

I have to say that this plugin is really cool and helpful! :)

However, I have found a few issues related to reporting of release versions, and I couldn't find anyone else posting about it, so I am adding this new issue. 

I have a simple Spring Boot, reactive, restful web service, that I created using Spring Initializr a few weeks ago.  I have properly configured my project and the Gradle-Kotin-Dsl-Libs ("GKDL"), and it generates the Libs and Versions files, as expected.  However, the version information for the following items is incorrect, since it does not match the versions that I started with, nor what Spring Initializr generates.  I've noticed that these issues appear in the first and the last two entries in the Libs file that is generated.  Has anyone noticed this issue?  If I can provide any more information, please let me know...

Thank you for your time,

Mike

----------------------------

* org_springframework_cloud: 
    Versions => "2.1.0.RELEASE"; 
    Should be "Greenwich.BUILD-SNAPSHOT";

* spring_boot_starter_webflux: 
    Versions => "none"; 
    Should be "2.1.0.RELEASE";

* jackson_module_kotlin: 
    Versions => "none"; 
    Should be "2.9.7";

VERSION INFORMATION
IntelliJ: 2018.2.6
Java: 11.0.1
Kotlin: 1.3.10
Kotlin DSL: 1.0.4
Gradle: 5.0
Shadow: 4.0.2
Gradle-Kotin-Dsl-Libs: 0.2.6
Spring Boot: 2.1.0.RELEASE
Spring Cloud: 2.1.0.RELEASE, but should be Greenwich.BUILD-SNAPSHOT

[Files.zip](https://github.com/jmfayard/gradle-kotlin-dsl-libs/files/2621662/Files.zip)

**Comment by jmfayard** [comment]
Hello @abitofhelp 

1. I hadn't tried the plugin yet with Gradle 5.0, so thanks for telling me that it works 👍 
2. For an immediate workaround of the problem, feel free to modify directly `Versions.kt`. 

```diff
object Versions {
-    const val jackson_module_kotlin: String = "none"
+    const val jackson_module_kotlin: String = "2.9.7"
}
```

3. Please search the file `build/..../report.json` 
What are the parts that correspond to `spring_boot_starter_webflux, org_springframework_cloud, jackson_module_kotlin` ? 

4. The above file is generated by the task `:dependencyUpdates` from https://github.com/ben-manes/gradle-versions-plugin

Your problem may be that you need to configure another repository, which worked for another user. Have a look here:
https://github.com/ben-manes/gradle-versions-plugin/issues/274

Also by default I reject snapshot release informatinon who generates a lot of noise 
"2.1.0.RELEASE"  "Greenwich.BUILD-SNAPSHOT";
https://github.com/jmfayard/gradle-kotlin-dsl-libs/blob/master/src/main/kotlin/jmfayard/github/io/GradleKotlinDslLibsPlugin.kt#L17-L27

5. Using "none" when I have no version is not a great solution from my part. Maybe I should crash instead

```diff
object Versions {
-    const val jackson_module_kotlin: String = "none"
+    const val jackson_module_kotlin: String = 
+          error("Could not determine Version.jackson_module_kotlin. Please edit Versions.kt manually. See https://github.com/jmfayard/gradle-kotlin-dsl-libs/issues/23")
}
```

**Comment by gmariotti** [comment]
Hi @jmfayard, just to add to this discussion, I have the same issue and it seems to be affected only libraries that have their version set by a plugin, in my case:
- `org.jetbrains.kotlin:kotlin-stdlib-jdk8` from `org.jetbrains.kotlin.jvm"`
- `io.vertx:vertx-core` from `io.vertx.vertx-plugin`
This happens independently from which repositories I have set.

Any chance to have an option to not set the version for libraries that have it to `"none"`?

By the way, really a cool project, I was hoping that someone would figure it out how to sync `ben-manes` plugin with gradle `buildSrc`

**Comment by jmfayard** [comment]
Yes that can/will be fixed

**Comment by jmfayard** [comment]
I believe this is fixed
