### ISSUE TITLE
Exclude some subproject

### ISSUE THREAD

**Issue by JanVomlel** [jmfayard/buildSrcVersions#33]
My project contains deprecated applications. They use old dependecies. I would like to exclude them from syncLibs.

**Comment by jmfayard** [comment]
@JanVomlel What do you mean exactly by "exclude"?

**Comment by JanVomlel** [comment]
Your plugin is applied to root project and generate Libs.kt and Versions.kt from all dependencies in all subprojects. I would like to ignore some subprojects and their dependecies do not add to Libs.kt and Versions.kt.
