### ISSUE TITLE
Libs name changing when updated

### ISSUE THREAD

**Issue by WhosNickDoglio** [jmfayard/buildSrcVersions#40]
When I run `buildSrcVersions` to update my Libs sometimes certain Libs will change their names and break Gradle sync. This seems to happen most often with the Kotlin standard library, but has also happened with Dagger.

The Kotlin standard library jumps between `kotlin_stdlib_jdk8` and `org_jetbrains_kotlin_kotlin_stdlib_jdk8`.

while Dagger will sometimes add `com_google` as a prefix. 

`dagger` -> `com_google_dagger`
`dagger_compiler` ->`com_google_dagger_compiler`

**Comment by jmfayard** [comment]
Hello @WhosNickDoglio 

It may be a bug, but it's also supposed to happen when a name collision is detected. Let say you have two dependencies:

```
  implementation("com.google.dagger:dagger:2.21")
  implementation("com.zsc.core:dagger:")
```

Then the plugin is using the FDQN `com_google_dagger_dagger` to avoid the name collision with the other dependency. I'm not sure why it happens with "kotlin_stdlib_jdk8" though. 

Did it jump only once from the simple name to the FDQN or was it back and froth? 

In the second case that would be annoying, and one thing you could do is to force the plugin to always use the FDQN:

```
buildSrcVersions {
    useFdqnFor.set(listOf("dagger", "kotlin-stdblib-jdk8"))
}
```

(That's the Kotlin DSL syntax, the groovy one is a bit different)

**Comment by WhosNickDoglio** [comment]
> Did it jump only once from the simple name to the FDQN or was it back and forth?

It's jumping back and forth, it's happened quite a few times with "kotlin_stdlib_jdk8" , the dagger libraries have maybe only jumped once or twice. 

I'll try adding the suggested block of code and will update if the issue pops up again, thanks!

**Comment by WhosNickDoglio** [comment]
After adding the suggested block of code I'm no longer seeing this issue with any of my projects.

Closing this issue 👍
