### ISSUE TITLE
Support for Gradle plugins using "id"

### ISSUE THREAD

**Issue by jschneider** [jmfayard/buildSrcVersions#44]
I am using Kotlin as language and adding plugins by calling:

`id("de.fayard.buildSrcVersions") version "0.4."`

I am able to use the generated version number by calling:

`id("de.fayard.buildSrcVersions") version Versions.de_fayard_buildsrcversions_gradle_plugin`

Unfortunately the string "de.fayard.buildSrcVersions" is *not* created in Libs. What about creating a third object named "Plugins"?

Wish:
`id(Plugins.buildSrcVersions) version Versions.de_fayard_buildsrcversions_gradle_plugin`

PS: Great plugin - I love the idea of autogenerating the files and adding comments for newer versions! That is really great!

**Comment by jmfayard** [comment]
@jschneider can you try to create manually the `Plugins` object in the buildSrc and see if that works? 
I remember that Gradle was really restrictive on what can be done in the `plugins { ... }` block

**Comment by jschneider** [comment]
Well, it does work with build.gradle.kts files.

I am creating the Plugins object currently. This is what I find very, very helpful:


```
import org.gradle.kotlin.dsl.kotlin
import org.gradle.plugin.use.PluginDependencySpec

object Plugins {
  const val dokka: String = "org.jetbrains.dokka"
  const val shadow: String = "com.github.johnrengelman.shadow"
  const val buildSrcVersions: String = "de.fayard.buildSrcVersions"
  const val kotlinxSerialization: String = "kotlinx-serialization"
  const val download: String = "de.undercouch.download"
}

inline val org.gradle.plugin.use.PluginDependenciesSpec.kotlinJvm: PluginDependencySpec
  get() = kotlin("jvm")

inline val org.gradle.plugin.use.PluginDependenciesSpec.kotlinStdLibJdk8: PluginDependencySpec
  get() = kotlin("stdlib-jdk8")

inline val org.gradle.plugin.use.PluginDependenciesSpec.kotlinMultiplatform: PluginDependencySpec
  get() = kotlin("multiplatform")

inline val org.gradle.plugin.use.PluginDependenciesSpec.kotlinxSerialization: PluginDependencySpec
  get() = id(Plugins.kotlinxSerialization)

inline val org.gradle.plugin.use.PluginDependenciesSpec.shadow: PluginDependencySpec
  get() = id(Plugins.shadow)

inline val org.gradle.plugin.use.PluginDependenciesSpec.launch4j: PluginDependencySpec
  get() = id(Plugins.launch4j)

inline val org.gradle.plugin.use.PluginDependenciesSpec.download: PluginDependencySpec
  get() = id(Plugins.download)

```

You get the idea? 
I use the string constants  with "apply" and the extension methods within a "plugins" block

**Comment by jmfayard** [comment]
@jschneider
Any reason to not include the version like this?
 
```kotlin
inline val org.gradle.plugin.use.PluginDependenciesSpec.kotlinJvm: PluginDependencySpec
  get() = kotlin("jvm").version(Versions.org_jetbrains_kotlin_jvm_gradle_plugin)
```

**Comment by jschneider** [comment]
Good point. Thanks! Will give it a try.

**Comment by jmfayard** [comment]
@jschneider As a first step, I added an accessor for the plugin itself, so that it's easy to update its version. 

https://github.com/jmfayard/buildSrcVersions/issues/47

If you want to see if it can be generalized, look here
 
https://github.com/jmfayard/buildSrcVersions/blob/6a1afb4ec8b5c6c26d3d1b65f42b6e445332e93c/plugin/src/main/kotlin/de/fayard/KotlinPoetry.kt#L92-L102

**Comment by jschneider** [comment]
One think about the version: The version can only be set once for a plugin (e.g. in the top level build.gradle.kts with apply false).

**Comment by jmfayard** [comment]
@jschneider I have no plans to have the plug-in generate a `Plugins.kt` file. Seems too hard to do correctly in all cases. Writing it manually like in your example is the best solution imho
