### ISSUE TITLE
Support different code style

### ISSUE THREAD

**Issue by jschneider** [jmfayard/buildSrcVersions#45]
I am using two spaces indentation. The autogenerated file uses 4 spaces.
Whenever I am editing and committing the versions file, everything has changes.

I would love to be able to configure the code style (or maybe pick it up from the .editorconfig file?)

**Comment by jschneider** [comment]
There is also a training spaces after the version number in the Versions file

**Comment by jschneider** [comment]
Also the max length of the line should be configurable. (KotlinPoetry:114)

**Comment by jmfayard** [comment]
> There is also a training spaces after the version number in the Versions file

This, I believe, has been fixed by runningcode's PR https://github.com/jmfayard/buildSrcVersions/pull/43 released in `0.4.0`

> I am using two spaces indentation. The autogenerated file uses 4 spaces.
Whenever I am editing and committing the versions file, everything has changes.
> I would love to be able to configure the code style (or maybe pick it up from the .editorconfig file?)

**Comment by jmfayard** [comment]
@jschneider In version 0.4.2, you can configure the plugin to use two spaces indentation 
https://github.com/jmfayard/buildSrcVersions/issues/53
