### ISSUE TITLE
Provide `apply plugin` configuration

### ISSUE THREAD

**Issue by Ghedeon** [jmfayard/buildSrcVersions#49]
Probably not everyone migrated to `plugins {}` syntax and I expect the old format to stick for a while. Would be nice to have both options documented. It took some googling to discover that the classpath is `classpath 'de.fayard.buildSrcVersions:de.fayard.buildSrcVersions.gradle.plugin:0.4.1'`

**Comment by jmfayard** [comment]
It's documented on the Gradle plugins page
https://plugins.gradle.org/plugin/de.fayard.buildSrcVersions

**Comment by Ghedeon** [comment]
That's also true for the `plugins {}` :). It's just a nice thing to do, assuming that AS still generates projects using the old syntax. Here is a relevant PR: https://github.com/jmfayard/buildSrcVersions/pull/51.
