### ISSUE TITLE
import kotlin.String necessary?

### ISSUE THREAD

**Issue by jschneider** [jmfayard/buildSrcVersions#54]
Since 4.0.2 an import to kotlin.String is created in the Versions.kt.
I am not sure but suspect, that this import is redundant. So maybe skip it?

**Comment by jmfayard** [comment]
The KotlinPoet has unit tests check that the lines `import java.lang.Object` or `import kotlin.Boolean` are present. 
https://github.com/square/kotlinpoet/blob/485a9b5cc3fe09b9e422b97926fa120ad9031450/kotlinpoet/src/test/java/com/squareup/kotlinpoet/AnnotationSpecTest.kt#L323-L324

I don't really know why they decided to add those redundant imports and am too lazy to check that with them.

**Comment by jmfayard** [comment]
Reason stated by KotlinPoet in the issue opened by LouisCAD:

> Unfortunately they're necessary because if you define a class with a conflicting name in your own package it will take precedence.

So those imports are here to stay
