### ISSUE TITLE
Version strange from JitPack.io

### ISSUE THREAD

**Issue by IgorGanapolsky** [jmfayard/buildSrcVersions#63]
I published my own lib on JitPack: https://jitpack.io/#IgorGanapolsky/seekarc/v1.2.0
In my gradle file am importing it as follows:
`implementation 'com.github.IgorGanapolsky:SeekArc:v1.2.0'`

However, your plugin states: 
>  // available: "1.2"

Can you please advise of the correct behavior?

**Comment by jmfayard** [comment]
I will have to look how the plugin works with JitPack.
Is your library also published on jCenter or mavenCentral()

**Comment by IgorGanapolsky** [comment]
Just JitPack

**Comment by jmfayard** [comment]
Website jitpack.io seems down :(

**Comment by jmfayard** [comment]
Closing for now, please re-open if this is still an issue and you have reproducing steps
