### ISSUE TITLE
Order by length / alphabetical

### ISSUE THREAD

**Issue by jmfayard** [jmfayard/buildSrcVersions#65]
I am stealing from Ben Manes the idea to sort dependencies not by a boring alphabetical order, but in an esthetically pleasing way:

```kotlin
// <buildSrcVersions>
// Generated by ./gradle buildSrcVersions
// See https://github.com/jmfayard/buildSrcVersions/issues/54
val org_jetbrains_kotlin_jvm_gradle_plugin = "1.3.50"
val org_jetbrains_kotlin = "1.3.50"
val okhttp = "4.1.0" // available: "4.1.1"
val okio = "2.0.0"
// </buildSrcVersions>
```

This is by default in the new `singleVersionMode`. 

I don't want to pollute the pull requests of projects already using `Versions.kt|Libs.kt` so I will keep the existing order for the. 

But if no `Versions.kt` is present, I will use the new order. 

If you are already using the project and wants to migrate, here is a recommended work-around: 

- Rename `Versions.kt` to `Versions-old.kt`
- Run `$ ./gradlew buildSrcVersions` 
- Delete `Versions-old.kt`

**Update:** this is not configurable at the moment but if someone feel strongly that alphabetical order is better, feel free to submit a pull-request.

**Comment by jmfayard** [comment]
Done

**Comment by vlsi** [comment]
Is there opt-out to still get alphabetical sort order?

**Comment by jmfayard** [comment]
Currently no

**Comment by ben-manes** [comment]
haha, I don't sort by length! Its by group, module, version ([Dependency.groovy](https://github.com/ben-manes/gradle-versions-plugin/blob/master/src/main/groovy/com/github/benmanes/gradle/versions/reporter/result/Dependency.groovy)).

**Comment by jmfayard** [comment]
This is inspired by this:

![image](https://user-images.githubusercontent.com/459464/64755479-4174e280-d52b-11e9-8c26-433885ee0bf4.png)

I tried it and liked it so much that I will keep it until someone feel strongly enough about it to submit a pull-request to make it configurable :)

**Comment by ben-manes** [comment]
oh! =)

In the report its by coordinate for logical groupings. Then related dependencies, like jackson and its modules, are together. That might make sense for you, might not.

**Comment by jschneider** [comment]
I have these two entries in Versions.kt:

  const val kotlinx_serialization_runtime_common: String = "0.13.0"
  const val kotlinx_serialization_runtime: String = "0.13.0"

There are *not* placed next to each other. Any ideas what went wrong there? Since they (obviously) share the same prefix and the same version number, I'd prefer them to have them next to each other.

**Comment by jschneider** [comment]
Sorry I have to come back to this. But I really hate the feature now. It makes it harder to find what I am looking for.

But it looks nice ;-). So there is that.

**Comment by jmfayard** [comment]
`Ctrl-F` works for me but I accept pull requests to make it a setting.

**Comment by jschneider** [comment]
Yep. Ctrl-F works for finding - but does not replace grouping. Asking for PR is fair however ;-)

**Comment by jmfayard** [comment]
And that shouldn't be very hard
https://github.com/jmfayard/buildSrcVersions/blob/e117dc0898aadbc1fce1029a87c48d5aa0ce269c/plugin/src/main/kotlin/de/fayard/internal/KotlinPoetry.kt#L59-L60

**Comment by jmfayard** [comment]
@jschneider I implemented this in v.7.0
https://github.com/jmfayard/buildSrcVersions/issues/53

Note that I am in the process of renaming the project
https://github.com/jmfayard/buildSrcVersions/issues/104
