### ISSUE TITLE
Always tries to update de_fayard_buildsrcversions_gradle_plugin

### ISSUE THREAD

**Issue by GuilhE** [jmfayard/buildSrcVersions#87]
Every time I run `./gradlew buildSrcVersions` it says I have to "update" your lib. But as you can see:

![Screenshot 2019-09-25 at 17 28 20](https://user-images.githubusercontent.com/2677139/65620558-f2fb2580-dfb9-11e9-8d62-c9c50254cf31.png)

I was already using the latest version.

**Comment by jmfayard** [comment]
@GuilhE Can you show me what you have in the `plugins { ...} ` block in `build.gradle(.kts)`?

**Comment by GuilhE** [comment]
@jmfayard:
```
plugins {
    `kotlin-dsl`
}
repositories {
    mavenCentral()
}
```

**Comment by jmfayard** [comment]
@GuilhE sorry, this `buildSrc/build.gradle.kts`, I mean `./build.gradle`.
But even without that information, my guess that updating the plugin version does nothing, because it's not used by your build. The task always regerenate the version currently used by your build. 
There isn't a great way yet to configure plugin versions inside the buildSrc. 
I will release this as part of version 0.6.2, I will ping you when it's ready.

**Comment by GuilhE** [comment]
Oh I get it:
```
plugins{
    id "de.fayard.buildSrcVersions" version "0.4.2"
}
```
Yes this version was unchanged, makes sense the behaviour.
Sure, ping me, I'm glad I can help, and thanks for this great plugin!

**Comment by jmfayard** [comment]
@GuilhE 
v0.6.2 is released https://github.com/jmfayard/buildSrcVersions/releases/tag/v0.6.2

Have a look at the new `:refreshVersions` files and how it can be leveraged to configure plugin versions (if you upgrade to Gradle 5.6.2)

https://github.com/jmfayard/buildSrcVersions/issues/77

**Comment by GuilhE** [comment]
Hello @jmfayard 
Well actually using `gradle.properties` over `Libs` it's a step back for me, auto-complete it's important. I prefer `:buildSrcVersions` intead of `:refreshVersions`.
I haven't noticed by the time but [this](https://github.com/jmfayard/buildSrcVersions/issues/47) is the solution I was searching, I have to migrate my build.gradle to .kts though.

**Comment by jmfayard** [comment]
@GuilhE `gradle.properties` does not replace `Libs.kt`, it replaces `Versions.kt`

You can use at the same time `:refreshVersions` to update the versions and `:buildSrcVersions` to generate `Libs.kt` and use auto-complete everywhere. 

You can also use only `:buildSrcVersions` if you prefer. `Versions.kt`  will still be generated unless `plugin.de.fayard.buildSrcVersions`  is found in `gradle.properties`

Beware  that `v0.6.2` is broken, better use `v0.6.3`

**Comment by GuilhE** [comment]
@jmfayard ok I had the wrong impression because I was searching for a `implementation(Libs.something)` in your `sample-kotlin` and it was missing. I've also took a look in your [blog ](https://dev.to/jmfayard/configuring-gradle-with-gradle-properties-211k#putting-there-your-own-settings) and it wasn't clear for me. My bad ^^

> Or you can also use only :buildSrcVersions if you prefer. Versions.kt will still be generated unless plugin.de.fayard.buildSrcVersions is found in gradle.properties

I'll stick with this solution for now, but I'll also try the `:refreshVersions`

> Beware that v0.6.2 is broken, better use v0.6.3

Yes I was following the issue open by the other user, I had the same problem but I was in the middle of the Groovy to Kotlin translation so I didn't pay attention.` v0.6.3` fixes the issue :)

**Comment by jmfayard** [comment]
@GuilhE well I have the goal to be clear, so if you didn't understand it, it's also "my bad". Is that clearer like this? https://github.com/jmfayard/buildSrcVersions/issues/77

**Comment by GuilhE** [comment]
@jmfayard it's perfect! :)
